CREATE TABLE T_ESTOQUE (
    ID_ESTOQUE NUMBER,
    CD_PRODUTO NUMBER,
    CD_ARMAZEM NUMBER,
    QT_PRODUTO NUMBER
);

INSERT INTO T_ESTOQUE (ID_ESTOQUE, CD_PRODUTO, CD_ARMAZEM, QT_PRODUTO)
VALUES (1, 1015, 1, 10);

INSERT INTO T_ESTOQUE (ID_ESTOQUE, CD_PRODUTO, CD_ARMAZEM, QT_PRODUTO)
VALUES (2, 1015, 2, 0);
