CREATE TABLE T_ESTOQUE (
    ID_ESTOQUE INT,
    CD_PRODUTO INT,
    CD_ARMAZEM INT,
    QT_PRODUTO INT
);

INSERT INTO T_ESTOQUE (ID_ESTOQUE, CD_PRODUTO, CD_ARMAZEM, QT_PRODUTO)
VALUES (1, 1015, 1, 10);

INSERT INTO T_ESTOQUE (ID_ESTOQUE, CD_PRODUTO, CD_ARMAZEM, QT_PRODUTO)
VALUES (2, 1015, 2, 0);
